desc "Example of automatically provisioning test devices as well as building and distributing an app to those devices"
lane :distribute do
  # Any actions used in this example outside of appcenter_fetch_devices and appcenter_upload ship with fastlane

  # Fetch the list of all iOS devices your app is distributed to
  appcenter_fetch_devices(
    api_token: "<appcenter token>",
    owner_name: "<appcenter account name of the owner of the app (username or organization URL name)>",
    app_name: "<appcenter app name>",
    destinations: "*",
    devices_file: "test-devices.txt"
  )

  # Ensure all devices are registered with Apple
  register_devices(devices_file: "test-devices.txt")

  # Provision test devices, download provisioning profile, and download signing certificate
  match(force_for_new_devices: true)

  # Build the app
  gym

  # Upload the app
  appcenter_upload(
    # All required parameters are propagated from the above actions
  )
end
