# load variables from .env file in the root if it exists
if File.exist?('../.env')
  open('../.env', 'r').readlines.each do |l|
    kv = l.split('=')
    ENV[kv[0]] = kv[1].chomp
  end
end

lane :test_autocreation do
  # app should be autocreated if not found
  appcenter_upload(
    api_token: ENV["TEST_APPCENTER_API_TOKEN"],
    owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
    app_name: "MyApplication-notfound-2",
    apk: "./fastlane/app-release.apk"
  )
end

lane :test_release_notes do
  appcenter_upload(
    api_token: ENV["TEST_APPCENTER_API_TOKEN"],
    owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
    app_name: "MyApplication-01",
    ipa: "./fastlane/app-release.ipa",
    group: ENV["TEST_APPCENTER_DISTRIBUTE_GROUP"],
    release_notes: sh("cat ./test_CHANGELOG.md")
  )
end

lane :test do
  # appcenter_upload will read release_notes from FL_CHANGELOG
  Actions.lane_context[SharedValues::FL_CHANGELOG] = 'shared changelog'

  UI.message("\n\n\n=====================================\n uploading android\n=====================================")

  appcenter_upload(
    api_token: ENV["TEST_APPCENTER_API_TOKEN"],
    owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
    app_name: "MyApplication",
    apk: "./fastlane/app-release.apk"
  )

  UI.message("\n\n\n=====================================\n uploading ios with dSYM files (not zipped) \n=====================================")

  appcenter_upload(
    api_token: ENV["TEST_APPCENTER_API_TOKEN"],
    owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
    app_name: "MyApplication-01",
    ipa: "./fastlane/app-release.ipa",
    group: ENV["TEST_APPCENTER_DISTRIBUTE_GROUP"],
    release_notes: ENV["TEST_APPCENTER_DISTRIBUTE_RELEASE_NOTES"]
  )

  UI.message("\n\n\n=====================================\n uploading only dSYM files (not zipped) \n=====================================")

  appcenter_upload(
    api_token: ENV["TEST_APPCENTER_API_TOKEN"],
    owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
    app_name: "MyApplication-01",
    upload_dsym_only: true,
    dsym: "./fastlane/Themoji.dSYM",
    release_notes: ENV["TEST_APPCENTER_DISTRIBUTE_RELEASE_NOTES"]
  )

  UI.message("\n\n\n=====================================\n uploading to multiple groups \n=====================================")  

  appcenter_upload(
    api_token: ENV["TEST_APPCENTER_API_TOKEN"],
    owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
    app_name: "MyApplication",
    apk: "./fastlane/app-release.apk",
    group: ENV["TEST_APPCENTER_DISTRIBUTE_GROUPS"],
  )

end
