trigger:
- master

pr:
- master

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
name: $(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

extends:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  ${{ else }}:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure Pipelines
      image: macos-latest
      os: macOS
    customBuildTags:
    - ES365AIMigrationTooling-BulkMigrated
    sdl:
      sourceAnalysisPool: 1ES-PT-Windows-2022
    stages:
    - stage: Stage
      jobs:
      - job: HostJob
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: "Publish Artifact: artifacts"
            path: '$(Build.ArtifactStagingDirectory)/npm'
            artifactName: npm
            
        steps:
        - task: UseRubyVersion@0
          displayName: 'Use Ruby 3.1.x'
          inputs:
            versionSpec: '3.1.x'

        - bash: |
            gem install bundler
            bundle install --retry=3 --jobs=4
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Bundle install'

        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/npm/$(Build.BuildId).tgz'
            replaceExistingArchive: true
            verbose: true
          displayName: 'Prepare release artifact'

       - task: APIScan@2
           displayName: Run APIScan
           inputs:
             softwareFolder: $(Build.ArtifactStagingDirectory)/npm
             softwareName: 'fastlane-plugin-appcenter-1ES'
             softwareVersionNum: '$(Build.BuildId)'
             isLargeApp: false
             toolVersion: 'Latest'
           condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
           env:
             AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);KeyVaultCertificateSecretIdentifier=$(KeyVaultCertificateSecretIdentifier)